### ISSUE TITLE
Попробуй сделать с одним циклом и без массивов

### ISSUE THREAD

**Issue by AnPogrebnyak** [IhorTerletskyi/My-first-programs#16]
https://github.com/IhorTerletskyi/My-first-programs/blob/a635d6a99371eae8655cd460c41a6bf21710df99/Calculator.java#L4

**Comment by IhorTerletskyi** [comment]
Я постарался оптимизировать программу, выкинул пару ненужных массивов... Но совсем в один цикл и без массивов не могу придумать...

**Comment by AnPogrebnyak** [comment]
Ок, пусть будет так.
У нас не олимпиада по программированию )
