### ISSUE TITLE
Сделай зеркальный разворот при помощи цикла для массива произвольной длины

### ISSUE THREAD

**Issue by AnPogrebnyak** [IhorTerletskyi/My-first-programs#2]
https://github.com/IhorTerletskyi/My-first-programs/blob/ba21ca60942cdb87cf2367aa410513741fc6c25f/Lesson3.java#L81

**Comment by IhorTerletskyi** [comment]
Все ДЗ с 3 урока переделал с циклами, находится в файле Lesson3New.java
