### ISSUE TITLE
Сделай для массива произвольной длины

### ISSUE THREAD

**Issue by AnPogrebnyak** [IhorTerletskyi/My-first-programs#5]
https://github.com/IhorTerletskyi/My-first-programs/blob/ba21ca60942cdb87cf2367aa410513741fc6c25f/Lesson4.java#L60

**Comment by IhorTerletskyi** [comment]
Заменил длину известного массива на универсальную переменную array1020.length-1, которая была бы применима к массиву любой длины, но массив в задании использую тот же.
