### ISSUE TITLE
Однобуквенные переменные усложняют понимание кода!

### ISSUE THREAD

**Issue by AnPogrebnyak** [IhorTerletskyi/My-first-programs#6]
https://github.com/IhorTerletskyi/My-first-programs/blob/ba21ca60942cdb87cf2367aa410513741fc6c25f/Lesson4.java#L87

**Comment by IhorTerletskyi** [comment]
Именно в этом случае поменял, т.к. тут их две. В остальных случаях оставлял i.

**Comment by AnPogrebnyak** [comment]
Никогда и нигде не используй однобуквенные переменные.
